### ISSUE TITLE
Add custom MC-Dev import example

### ISSUE THREAD

**Issue by lexikiq** [PaperMC/paperweight-examples#1]
would be helpful (for me, and i'm sure for others) to have an example on how mcDev imports work with the new tooling 😅 ❤️

**Comment by MiniDigger** [comment]
you should be able use any file from papers build-data folder in a fork too:
https://github.com/PaperMC/paperweight-examples/commit/de3cac8793a2891ae55b6a7241cafca2c7272959

**Comment by lexikiq** [comment]
Ah, I thought I'd seen a file like that somewhere but couldn't find it again... Thank you!

**Comment by MiniDigger** [comment]
https://github.com/PaperMC/Paper/tree/dev/1.17/build-data
the AT file is also cool ;)

**Comment by lexikiq** [comment]
AT file doesn't seem to be working for me- i've triple checked all the paths are right and i've matched the format of ATs in paper
![image](https://user-images.githubusercontent.com/13265322/122655100-fc2d0e00-d11d-11eb-97e9-da4be3c5c912.png)

file is `build-data/paper.at` (i've tried other names as well)
