### ISSUE TITLE
fatal: Needed a single revision

### ISSUE THREAD

**Issue by marsonplay** [PaperMC/paperweight-examples#21]
/gradlew createReobfPaperclipJar
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
Configuration on demand is an incubating feature.
fatal: Needed a single revision

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':createReobfBundlerJar'.
> Could not resolve all dependencies for configuration ':mirai-server:runtimeClasspath'.
   > Could not create task ':mirai-server:jar'.
      > Command finished with 128 exit code: git -c commit.gpgsign=false -c core.safecrlf=false rev-parse --short=7 HEAD

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by electronicboy** [comment]
Make sure that you cloned the repo and applied patches first, otherwise, not enough info here

**Comment by marsonplay** [comment]
Compilation to windows was causing errors They arrived and linux managed to solve it. sorry for replying so late :(
