### ISSUE TITLE
ApplyPatches failed on MacOS

### ISSUE THREAD

**Issue by derverdox** [PaperMC/paperweight-examples#24]
MacOS Version: 14.1.1 (23B81)
Tested on multiple IntelliJ Versions
Gradle Version: 8.4
Git Version: 2.39.3

How to reproduce:
1. Get project from VCS and clone this repository.
2. Execute paperweight applyPatches

What is the error:
First, the paper software is built in .gradle/caches
After that an error is thrown about local changes that cause the merge to fail. However, there are no local changes at all.

`12:56:54: Executing 'applyPatches'...

> Configure project :
paperweight-patcher v1.5.7 (running on 'Mac OS X')

> Task :clonePaperRepo

> Configure project :paper
paperweight-core v1.5.7 (running on 'Mac OS X')

> Task :paper:initSubmodules
> Task :paper:patchSpigotApiPatches FROM-CACHE
> Task :paper:patchSpigotApi

> Task :paper:applyApiPatches
error: Your local changes to the following files would be overwritten by merge:
	src/main/java/org/bukkit/block/DoubleChest.java
Please commit your changes or stash them before you merge.
Aborting
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
***   Please review above details and finish the apply then
***   save the changes with `./gradlew rebuildPatches`

> Task :paper:applyApiPatches FAILED
> Task :getPaperUpstreamData FAILED
2 actionable tasks: 2 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':paper:applyApiPatches'.
> io.papermc.paperweight.PaperweightException: Failed to apply patches

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 18s
12:57:13: Execution finished 'applyPatches'.`

**Comment by jpenilla** [comment]
Can't reproduce on my mac with the build cache populated. This is also not the correct place to ask for help or report issues with paperweight.
