### ISSUE TITLE
Does the AccessTransformer file work for Forks?

### ISSUE THREAD

**Issue by yannicklamprecht** [PaperMC/paperweight-examples#4]

**Comment by DenWav** [comment]
Not yet, it will when I can get to it.

**Comment by TheShermanTanker** [comment]
I'm currently trying to help add a PR for Reobf Mappings Patches, I'll try working on this next

**Comment by DenWav** [comment]
I know I'm taking a long time (which I'm sorry for) and I know you want to help (which I appreciate) but implementing that stuff is something I want to do myself. I apologize again for how long it's taken me to have the time.

**Comment by DenWav** [comment]
I see that you've already opened the PR. I'll review it and see how closely it aligns with what I am intending.

**Comment by TheShermanTanker** [comment]
> 
> 
> I know I'm taking a long time (which I'm sorry for) and I know you want to help (which I appreciate) but implementing that stuff is something I want to do myself. I apologize again for how long it's taken me to have the time.

There's no need to apologise, I know you're very busy and that isn't your fault, I just wanted to help out of goodwill to ease some of the burden of maintaining Paperweight is all :)

**Comment by yannicklamprecht** [comment]
What's the state currently?
