### ISSUE TITLE
Will auto updating of the Paperweight version of upstream to the same version as downstream be supported in the future?

### ISSUE THREAD

**Issue by TheShermanTanker** [PaperMC/paperweight-examples#8]

**Comment by yannicklamprecht** [comment]
Just add a patch to modify the version.

**Comment by TheShermanTanker** [comment]
> 
> 
> Just add a patch to modify the version.

I was referring to setting the version in the build.gradle.kts in the upstream repo that `paperweight-patcher` creates when run, I haven't managed to find a good way to do this so far other than directly changing the values in the kts files (Which is pretty ugly)
